-- Clinic Appointment System - reference schema
-- COMP713 Assignment 2 (Option A)
--
-- The application runs on an embedded H2 database whose schema is generated from the
-- JPA entities (spring.jpa.hibernate.ddl-auto=create-drop). This file documents the
-- equivalent schema: it is the authoritative reference for the tables, columns,
-- constraints, and the one-to-many relationship between patients and appointments.

-- A registered clinic patient. The e-mail address identifies a patient uniquely;
-- the service layer rejects duplicate registrations with HTTP 409 and this
-- constraint is the final protection when two registrations race.
CREATE TABLE patients (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    phone      VARCHAR(20),
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_patient_email UNIQUE (email)
);

-- A booked appointment slot belonging to one patient (patients.id 1 -> many).
-- * uk_appointment_patient_start: backstop against booking the same patient twice
--   at the same start time when concurrent requests race.
-- * ck_appointment_valid_range: an appointment must end after it starts.
-- Overlapping (but not identical) slots are enforced atomically by the
-- check-and-write statements in AppointmentSlotWritesImpl:
--   INSERT ... SELECT ... WHERE NOT EXISTS (overlap for this patient)
--   UPDATE ... WHERE id = ... AND NOT EXISTS (other overlap for this patient)
CREATE TABLE appointments (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT       NOT NULL,
    start_at   TIMESTAMP    NOT NULL,
    end_at     TIMESTAMP    NOT NULL,
    reason     VARCHAR(200),
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_appointment_patient      FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT uk_appointment_patient_start UNIQUE (patient_id, start_at),
    CONSTRAINT ck_appointment_valid_range  CHECK (end_at > start_at)
);

-- Overlap definition used everywhere in the application (touching end-to-start is
-- allowed, so back-to-back bookings do not conflict):
--   existing.start_at < :newEnd AND existing.end_at > :newStart

-- Demo data is seeded programmatically at startup by config/DemoDataConfiguration
-- (three patients, four upcoming weekday appointments), so the client pages are
-- immediately meaningful after `mvnw spring-boot:run`.
